-- Blue Coastal Atlas: fresh XAMPP MySQL schema. It creates no users, claims, reviews, or ratings.
CREATE DATABASE IF NOT EXISTS prachuap_directory CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE prachuap_directory;
CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,display_name VARCHAR(80) NOT NULL,role ENUM('member','business_owner','admin') NOT NULL DEFAULT 'member',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS places (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(140) NOT NULL UNIQUE,name VARCHAR(180) NOT NULL,category VARCHAR(80) NOT NULL,district VARCHAR(100) NOT NULL,subdistrict VARCHAR(100) NOT NULL,price_tier ENUM('unknown','budget','standard','premium') NOT NULL DEFAULT 'unknown',latitude DECIMAL(10,7) NULL,longitude DECIMAL(10,7) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,place_slug VARCHAR(140) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,rating TINYINT UNSIGNED NOT NULL,comment VARCHAR(1000) NOT NULL,status ENUM('pending','approved','hidden') NOT NULL DEFAULT 'pending',moderated_by BIGINT UNSIGNED NULL,moderated_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT rating_between_one_and_five CHECK (rating BETWEEN 1 AND 5),INDEX idx_reviews_place_status (place_slug,status,created_at),CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS loyalty_accounts (user_id BIGINT UNSIGNED PRIMARY KEY,points_balance INT UNSIGNED NOT NULL DEFAULT 0,lifetime_points INT UNSIGNED NOT NULL DEFAULT 0,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_loyalty_account_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS coupons (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,place_slug VARCHAR(140) NULL,store_name VARCHAR(160) NOT NULL,title VARCHAR(180) NOT NULL,description VARCHAR(800) NOT NULL,point_cost INT UNSIGNED NOT NULL,starts_at DATETIME NULL,ends_at DATETIME NULL,max_redemptions INT UNSIGNED NULL,redeemed_count INT UNSIGNED NOT NULL DEFAULT 0,status ENUM('pending_admin','active','inactive','rejected') NOT NULL DEFAULT 'pending_admin',created_by BIGINT UNSIGNED NULL,owner_id BIGINT UNSIGNED NULL,approved_by BIGINT UNSIGNED NULL,approved_at TIMESTAMP NULL,review_note VARCHAR(500) NOT NULL DEFAULT '',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_coupons_owner_status (owner_id,status,created_at),CONSTRAINT fk_coupon_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT fk_coupon_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT fk_coupon_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS coupon_redemptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,coupon_id BIGINT UNSIGNED NOT NULL,point_cost INT UNSIGNED NOT NULL,coupon_code VARCHAR(32) NOT NULL UNIQUE,status ENUM('issued','used','cancelled') NOT NULL DEFAULT 'issued',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,redeemed_at TIMESTAMP NULL,used_by BIGINT UNSIGNED NULL,used_at TIMESTAMP NULL,UNIQUE KEY uniq_user_coupon (user_id,coupon_id),INDEX idx_redemption_user_created (user_id,created_at),CONSTRAINT fk_redemption_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_redemption_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE RESTRICT,CONSTRAINT fk_redemption_used_by FOREIGN KEY (used_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS loyalty_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,review_id BIGINT UNSIGNED NULL UNIQUE,redemption_id BIGINT UNSIGNED NULL UNIQUE,event_type ENUM('review_approved','review_not_approved','coupon_redeemed') NOT NULL,points INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_loyalty_events_user_created (user_id,created_at),CONSTRAINT fk_loyalty_event_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_loyalty_event_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,CONSTRAINT fk_loyalty_event_redemption FOREIGN KEY (redemption_id) REFERENCES coupon_redemptions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS business_claims (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,place_slug VARCHAR(140) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,proof_note VARCHAR(1000) NOT NULL,status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',reviewed_by BIGINT UNSIGNED NULL,reviewed_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_claims_user_status (user_id,status),INDEX idx_claims_place_status (place_slug,status),CONSTRAINT fk_claims_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS claim_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,claim_id BIGINT UNSIGNED NOT NULL,stored_name VARCHAR(120) NOT NULL UNIQUE,original_name VARCHAR(180) NOT NULL,mime_type VARCHAR(100) NOT NULL,byte_size INT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_claim_documents_claim (claim_id),CONSTRAINT fk_claim_documents_claim FOREIGN KEY (claim_id) REFERENCES business_claims(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS business_updates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,place_slug VARCHAR(140) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,contact_note VARCHAR(300) NOT NULL DEFAULT '',hours_note VARCHAR(300) NOT NULL DEFAULT '',price_tier ENUM('unknown','budget','standard','premium') NOT NULL DEFAULT 'unknown',status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',reviewed_by BIGINT UNSIGNED NULL,reviewed_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_updates_status (status,created_at),CONSTRAINT fk_updates_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS place_views (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,place_slug VARCHAR(140) NOT NULL,event_type ENUM('detail_view') NOT NULL DEFAULT 'detail_view',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_views_place_created (place_slug,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS place_submissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,name VARCHAR(180) NOT NULL,category VARCHAR(80) NOT NULL,district VARCHAR(100) NOT NULL,subdistrict VARCHAR(100) NOT NULL,address_note VARCHAR(300) NOT NULL,contact_note VARCHAR(300) NOT NULL,hours_note VARCHAR(300) NOT NULL DEFAULT '',description VARCHAR(1500) NOT NULL,price_tier ENUM('unknown','budget','standard','premium') NOT NULL DEFAULT 'unknown',status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',approved_place_slug VARCHAR(140) NULL UNIQUE,reviewed_by BIGINT UNSIGNED NULL,reviewed_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_place_submissions_user_status (user_id,status,created_at),INDEX idx_place_submissions_status (status,created_at),CONSTRAINT fk_place_submissions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_place_submissions_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
